#import <Capacitor/Capacitor.h>

CAP_PLUGIN(BestTakeAudioPlugin, "BestTakeAudioPlugin",
    CAP_PLUGIN_METHOD(setHighQualityBluetoothMode, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setDeviceMicForRecording, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setBluetoothHeadphonePlaybackMode, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(reapplyHeadphonePlaybackRoute, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(enableStereoPlayback, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(enableRecordingRoute, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getPlaybackOutputProfile, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(startNativePlaybackTest, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(stopNativePlaybackTest, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(prepareCameraLikePlaybackSession, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setCameraSessionState, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(getCameraSessionState, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setPlaybackRouteActive, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(restoreRecordingRouteAfterPlayback, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(shareMediaFile, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(saveVideoToPhotos, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(renderCreatorStudioVideo, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(renderMultitrackVideo, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setNativeExperimentalAudioMode, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(startNativeCameraBridge, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(stopNativeCameraBridge, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(startNativeCameraPreview, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(stopNativeCameraPreview, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setNativeCameraPassthrough, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setNativeCameraFrameBridgeEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setNativeCameraPreviewZoom, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(setNativeAudioTapEnabled, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(enhanceTakeAudio, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(startNativeCameraRecording, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(stopNativeCameraRecording, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(playNativeCameraTestPostProcess, CAPPluginReturnPromise);
    CAP_PLUGIN_METHOD(stopNativeCameraTestPostProcess, CAPPluginReturnPromise);
)
